@startuml
start
: Пользователь открывает приложение;
if (Пользователь не авторизован) then
  : Пользователь регистрируется;
  : Пользователь подтверждает телефон;
  : Пользователь подтверждает email;
endif
  : Пользователь выбирает ресторан;
  : Пользователь просматривает меню;
  : Пользователь добавляет блюда в корзину;
  : Пользователь просматривает корзину;
  : Пользователь выбирает способ оплаты;
  if (Способ оплаты - карта?) then
    : Пользователь вводит данные карты;
    : Карта валидируется;
  else
    : Пользователь выбирает другой способ оплаты;
  endif
  : Пользователь оформляет заказ;
  : Заказ обрабатывается;
  : Пользователь получает уведомление о заказе;
  if (Заказ включает бронирование) then
    : Пользователь выбирает стол;
    : Стол бронируется;
    : Пользователь получает уведомление о бронировании;
  endif
  : Пользователь получает заказ;
stop
@enduml