@startuml
package "Мобильное приложение" {
  component "Клиентский интерфейс" as ClientInterface
  component "Логика приложения" as AppLogic
}

package "Бэкенд система" {
  component "Серверная логика" as ServerLogic
  component "СУБД PostgreSQL" as Database
  
  component "Сервис уведомлений" as Notifications
  component "Сервис отчетов" as ReportService
}

package "Внешние сервисы" {
  component "Платежная система" as PaymentSystem
  component "Google Maps" as GoogleMaps
}

ClientInterface -(0- AppLogic : использует
AppLogic -(0- ServerLogic : использует
AppLogic -(0- PaymentSystem : использует
AppLogic -(0- GoogleMaps : использует

ServerLogic -(0- Database : использует
ServerLogic -(0- Notifications : использует
ServerLogic -(0- ReportService : использует
@enduml