@startuml
object "Пользователь" as User
object "Система заказа" as OrderSystem
object "Менеджер ресторана" as RestaurantManager
object "Система оплаты" as PaymentSystem

User -> OrderSystem : Выбор блюд
User --> OrderSystem : Сделать заказ
OrderSystem --> RestaurantManager : Отправить информацию о заказе
RestaurantManager -> OrderSystem : Подтвердить заказ
OrderSystem --> PaymentSystem : Обработка платежа
PaymentSystem --> OrderSystem : Подтверждение платежа
OrderSystem --> User : Уведомление о статусе заказа

@enduml