@startuml
object "Пользователь" as User
object "Система заказа" as OrderSystem
object "Менеджер ресторана" as RestaurantManager
object "Система оплаты" as PaymentSystem

User -> OrderSystem : 1. Выбор блюд
User --> OrderSystem : 2. Сделать заказ
OrderSystem --> RestaurantManager : 3. Отправить информацию о заказе
RestaurantManager -> OrderSystem : 4. Подтвердить заказ
OrderSystem --> PaymentSystem : 5. Обработка платежа
PaymentSystem --> OrderSystem : 6. Подтверждение платежа
OrderSystem --> User : 7. Уведомление о статусе заказа

@enduml