@startuml
[*] --> Создан

Создан --> Ожидает_подтверждения : makeOrder()
Ожидает_подтверждения --> Подтвержден : confirmOrder()
Ожидает_подтверждения --> Отменен : cancelOrder()

Подтвержден --> В_приготовлении : startCooking()
В_приготовлении --> Готов_к_подаче : finishCooking()
Готов_к_подаче --> Подан : startDelivery()

Подан --> [*]
Отменен --> [*]
@enduml