@startgantt
Project starts 2024-10-01
printscale weekly zoom 2

-- Фаза А. Определение плана --

[Анализ требований] on {\nБизнес-аналитик, UX-исследователь} requires 10 days
[Составление бюджета] on {\nФинансовый аналитик, Менеджер проекта} requires 12 days
[Определение сроков проекта] on {\nМенеджер проекта, Планировщик} requires 5 days

[Составление бюджета] starts at [Анализ требований]'s end
[Определение сроков проекта] starts at [Составление бюджета]'s end

-- Фаза B: Разработка бизнес-архитектуры --

[Исследование рынка] on {\nМаркетолог, Аналитик рынка, UX-исследователь} requires 15 days
[Определение целевой аудитории] on {\nМаркетолог, Бизнес-аналитик} requires 10 days

[Исследование рынка] starts at [Определение сроков проекта]'s end
[Определение целевой аудитории] starts at [Исследование рынка]'s end

-- Фаза C: Разработка архитектуры данных и приложений --

[Проектирование системы управления заказами] on {\nАрхитектор системы, Разработчик ПО, Бизнес-аналитик} requires 20 days
[Разработка мобильного приложения для клиентов] on {\nМобильный разработчик, UI/UX-дизайнер, Тестировщик} requires 15 days

[Проектирование системы управления заказами] starts at [Определение целевой аудитории]'s end
[Разработка мобильного приложения для клиентов] starts at [Проектирование системы управления заказами]'s end

-- Фаза D: Разработка технологической архитектуры --

[Выбор поставщиков оборудования] on {\nМенеджер по закупкам, Инженер по оборудованию} requires 15 days
[Настройка программного обеспечения] on {\nСистемный администратор, Инженер по внедрению ПО, Разработчик ПО} requires 20 days

[Выбор поставщиков оборудования] starts at [Разработка мобильного приложения для клиентов]'s end
[Настройка программного обеспечения] starts at [Выбор поставщиков оборудования]'s end

-- Фаза E: Проверка возможности реализации решений --

[Оценка рисков и узких мест] on {\nМенеджер проекта, Аналитик рисков} requires 10 days
[Подготовка отчета о рисках] on {\nАналитик рисков, Менеджер проекта} requires 5 days

[Оценка рисков и узких мест] starts at [Настройка программного обеспечения]'s end
[Подготовка отчета о рисках] starts at [Оценка рисков и узких мест]'s end

-- Фаза F: Планирование перехода к новой системе --

[Разработка плана внедрения] on {\nМенеджер проекта, Специалист по внедрению, Бизнес-аналитик} requires 15 days
[Обучение персонала] on {\nТренер, Специалист по внедрению, Менеджер проекта} requires 10 days

[Разработка плана внедрения] starts at [Подготовка отчета о рисках]'s end
[Обучение персонала] starts at [Разработка плана внедрения]'s end

@endgantt